"""AI client integration helpers — pure functions, no FastAPI deps.

Each supported client gets a small dict describing:
- `key`        — URL slug used in /api/integrations/<key>/rules.
- `label`      — human-readable name shown on the page card.
- `config_file`— path the user pastes the snippet into (informational).
- `rules_file` — recommended path for the AI rules file (relative to repo
  root); `None` for clients that don't read one.
- `snippet`    — JSON snippet pre-populated with the current interpreter
  and config path.
- `notes`      — short paragraph rendered under the snippet (optional).

The rules content itself is generated by `render_rules_for_sources`
below, the single source of truth for the recommended CLAUDE.md /
AGENTS.md / .cursor/rules/lynx.md body.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Optional


_MCP_TEMPLATE = {
    "mcpServers": {
        "lynx": {
            "command": "<python>",
            "args": ["-m", "lynx", "serve", "--config", "<config>"],
        }
    }
}


def _mcp_snippet(python_exe: str, config_path: Optional[Path]) -> str:
    cfg_str = str(config_path.resolve()) if config_path else "<path to config.json>"
    body = {
        "mcpServers": {
            "lynx": {
                "command": python_exe,
                "args": ["-m", "lynx", "serve", "--config", cfg_str],
            }
        }
    }
    return json.dumps(body, indent=2)


# Per-client metadata. Order = display order on the page.
_CLIENTS: list[dict] = [
    {
        "key": "claude",
        "label": "Claude Code (CLI + VS Code extension)",
        "config_file": "~/.claude/mcp_settings.json",
        "rules_file": "CLAUDE.md",
        "notes": "On Claude Desktop the file is "
                 "~/Library/Application Support/Claude/claude_desktop_config.json "
                 "(macOS) — same JSON shape.",
    },
    {
        "key": "cursor",
        "label": "Cursor",
        "config_file": ".cursor/mcp.json",
        "rules_file": ".cursor/rules/lynx.md",
        "notes": "Goes in the project root. Cursor reloads MCP servers on restart.",
    },
    {
        "key": "antigravity",
        "label": "Google Antigravity",
        "config_file": ".agents/mcp.json",
        "rules_file": "AGENTS.md",
        "notes": "Same MCP JSON format as Claude / Cursor.",
    },
    {
        "key": "aider",
        "label": "Aider / Continue.dev / generic stdio",
        "config_file": "(client-specific)",
        "rules_file": "AGENTS.md",
        "notes": "Aider doesn't speak MCP natively yet — use this command "
                 "as a stdio subprocess from your tooling.",
    },
]


def build_integrations(config_path: Optional[Path]) -> list[dict]:
    """Return the per-client list with snippet + rules paths filled in."""
    snippet = _mcp_snippet(sys.executable, config_path)
    out = []
    for c in _CLIENTS:
        out.append({**c, "snippet": snippet})
    return out


def get_client(key: str) -> Optional[dict]:
    for c in _CLIENTS:
        if c["key"] == key:
            return c
    return None


def render_rules_for_sources(
    source_names: list[str],
    has_graph: bool,
    has_git: bool,
) -> str:
    """Build the AI-client rules-file body for the configured sources.

    Tailored to which capabilities are actually available: graph-layer
    tool names appear only when at least one source has the graph layer
    enabled, and diff-search tool names appear only when at least one
    source has git_integration on.
    """
    lines: list[str] = [
        "# Code Reuse & Library Awareness",
        "",
        "This project exposes a local MCP server (Lynx) with semantic search",
        "over the configured sources. Use the tools BEFORE writing new code",
        "or guessing at library APIs.",
        "",
        "## Sources available",
        "",
    ]
    for n in source_names:
        lines.append(f"- `{n}` — pass it as the `source` argument of the tools below.")
    lines.append("")
    lines.append("- `search(query, source=...)` — semantic + lexical hybrid search.")
    lines.append("- `search(query, outline=true)` — same ranked hits, signatures only "
                 "(no bodies). Cheap triage for broad/exploratory queries or a large "
                 "top_k: scan the signatures, then read just the one body you need with "
                 "`find_definition` or its file:line. Use the default full search when "
                 "you'll work with the code right away.")
    lines.append("- `deep_search(queries, source=...)` — fallback for ambiguous queries.")
    if len(source_names) > 1:
        lines.append("")
        lines.append("When unsure which source has the answer, omit `source` to "
                     "search ALL sources at once.")
    lines.append("")
    lines.append("## When to search")
    lines.append("")
    lines.append("Before implementing any utility, interface, or pattern,")
    lines.append("search the codebase source first to avoid duplication.")
    lines.append("Before invoking a library API, search the relevant docs source")
    lines.append("if one exists — your training data may predate the version in use.")
    if has_graph:
        lines.append("")
        lines.append("## Code-aware structural queries (graph layer enabled)")
        lines.append("")
        lines.append("- `find_definition(symbol)` — where is X defined?")
        lines.append("- `find_usages(symbol)` — who calls X? typeof / generics included.")
        lines.append("- `find_tests_for(symbol)` — are there tests for X?")
        lines.append("- `find_similar(snippet)` — is there code similar to this?")
        lines.append("- `graph_query(operation, symbol)` — operations: callers, callees,")
        lines.append("  subclasses, superclasses, imports, neighbors, shortest_path,")
        lines.append("  overview (god nodes + communities), surprising_connections, status.")
    if has_git:
        lines.append("")
        lines.append("## Diff-aware search (git_integration enabled)")
        lines.append("")
        lines.append("- `search_diff(query)` — search only in files changed vs `main`.")
        lines.append("  Use during code review: 'I changed the discount logic — what else uses the same formula?'")
    lines.append("")
    lines.append("## How to search")
    lines.append("")
    lines.append("Describe what the code *does*, not its name. Semantic search")
    lines.append("beats `grep` precisely because it bridges synonyms.")
    lines.append("")
    return "\n".join(lines)
