"""AI client integration helpers — pure functions, no FastAPI deps.

Each supported client gets a small dict describing:
- `key`        — URL slug used in /api/integrations/<key>/rules.
- `label`      — human-readable name shown on the page card.
- `config_file`— path the user pastes the snippet into (informational).
- `rules_file` — recommended path for the AI rules file (relative to repo
  root); `None` for clients that don't read one.
- `snippet`    — JSON snippet pre-populated with the current interpreter
  and config path.
- `notes`      — short paragraph rendered under the snippet (optional).

The rules content itself is generated by `lynx.manager.init._generate_rules_file`
so the wizard and the UI never disagree on what we recommend.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Optional


_MCP_TEMPLATE = {
    "mcpServers": {
        "lynx": {
            "command": "<python>",
            "args": ["-m", "lynx", "serve", "--config", "<config>"],
        }
    }
}


def _mcp_snippet(python_exe: str, config_path: Optional[Path]) -> str:
    cfg_str = str(config_path.resolve()) if config_path else "<path to config.json>"
    body = {
        "mcpServers": {
            "lynx": {
                "command": python_exe,
                "args": ["-m", "lynx", "serve", "--config", cfg_str],
            }
        }
    }
    return json.dumps(body, indent=2)


# Per-client metadata. Order = display order on the page.
_CLIENTS: list[dict] = [
    {
        "key": "claude",
        "label": "Claude Code (CLI + VS Code extension)",
        "config_file": "~/.claude/mcp_settings.json",
        "rules_file": "CLAUDE.md",
        "notes": "On Claude Desktop the file is "
                 "~/Library/Application Support/Claude/claude_desktop_config.json "
                 "(macOS) — same JSON shape.",
    },
    {
        "key": "cursor",
        "label": "Cursor",
        "config_file": ".cursor/mcp.json",
        "rules_file": ".cursor/rules/lynx.md",
        "notes": "Goes in the project root. Cursor reloads MCP servers on restart.",
    },
    {
        "key": "antigravity",
        "label": "Google Antigravity",
        "config_file": ".agents/mcp.json",
        "rules_file": "AGENTS.md",
        "notes": "Same MCP JSON format as Claude / Cursor.",
    },
    {
        "key": "aider",
        "label": "Aider / Continue.dev / generic stdio",
        "config_file": "(client-specific)",
        "rules_file": "AGENTS.md",
        "notes": "Aider doesn't speak MCP natively yet — use this command "
                 "as a stdio subprocess from your tooling.",
    },
]


def build_integrations(config_path: Optional[Path]) -> list[dict]:
    """Return the per-client list with snippet + rules paths filled in."""
    snippet = _mcp_snippet(sys.executable, config_path)
    out = []
    for c in _CLIENTS:
        out.append({**c, "snippet": snippet})
    return out


def get_client(key: str) -> Optional[dict]:
    for c in _CLIENTS:
        if c["key"] == key:
            return c
    return None


def render_rules_for_sources(
    source_names: list[str],
    has_graph: bool,
    has_git: bool,
) -> str:
    """Reuse the wizard's rules generator so the two surfaces produce
    identical content. Kept here as a thin re-export so importers don't
    need to know about the init module."""
    from ..init import _generate_rules_file
    return _generate_rules_file(source_names, has_graph, has_git)
